### ISSUE TITLE
Настроить и сконфигурировать окружение

### ISSUE THREAD

**Issue by cadaverine** [tachyonizer/tachyonizer#2]
Добавить:
- [ ] eslint
- [x] package.json
- [ ] babel
- [ ] package.json
- [ ] CONTRIBUTING.md

upd.:
- [ ] husky
- [ ] lint-staged

**Comment by MoonW1nd** [comment]
Не забудь добавить [husky](https://github.com/typicode/husky) и [lint-staged](https://github.com/okonet/lint-staged) для `precommit` хуков.

**Comment by cadaverine** [comment]
перенес в [milestone](https://github.com/tachyonizer/tachyonizer/milestone/1)
