### ISSUE TITLE
Pre-commit hooks

### ISSUE THREAD

**Issue by cadaverine** [tachyonizer/tachyonizer#6]
- [x] husky
- [x] lint-staged

**Comment by MoonW1nd** [comment]
@cadaverine Если мы решим использовать [conventional-commits](https://github.com/conventional-commits/conventionalcommits.org/blob/master/content/v1.0.0-beta.2/index.ru.md), думаю следует еще добавить эти 2 пакепа на precommit-hooks:
- [commitlint](https://github.com/marionebl/commitlint)
- [angular-config-convetional](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional)

**Comment by cadaverine** [comment]
@MoonW1nd согласен
